import type { DiagramData } from '@org-hierarchy/sdk';

/** Multi-org staff canvas: no position coords → tidy tree; Tier-3 org cards for drill. */
export function buildStaffTreeData(): DiagramData {
  return {
    organizations: [
      { id: 'holding', name: 'Holding Corp', groupIds: [] },
      { id: 'ops', name: 'Operations', groupIds: [], parentOrgId: 'holding' },
      { id: 'sales', name: 'Sales', groupIds: [], parentOrgId: 'ops' },
      { id: 'eng', name: 'Engineering', groupIds: [], parentOrgId: 'ops' },
    ],
    groups: [],
    departments: [
      { id: 'ops-core', name: 'Ops Core', organizationId: 'ops' },
      { id: 'eng-core', name: 'Eng Core', organizationId: 'eng' },
    ],
    persons: [
      { id: 'p-ceo', fullName: 'Ada Holding' },
      { id: 'p-coo', fullName: 'Ben Ops' },
      { id: 'p-lead', fullName: 'Cara Lead' },
      { id: 'p-a', fullName: 'Dan Alpha' },
      { id: 'p-b', fullName: 'Eve Beta' },
      { id: 'p-eng-h', fullName: 'Fay EngHead' },
      { id: 'p-dev', fullName: 'Gus Dev' },
    ],
    positions: [
      {
        id: 'pos-ceo',
        title: 'CEO',
        organizationId: 'holding',
        groupIds: [],
        personId: 'p-ceo',
        status: 'filled',
        isTemporary: false,
        isHead: true,
      },
      {
        id: 'pos-coo',
        title: 'COO',
        organizationId: 'ops',
        departmentId: 'ops-core',
        groupIds: [],
        personId: 'p-coo',
        status: 'filled',
        isTemporary: false,
        isHead: true,
      },
      {
        id: 'pos-lead',
        title: 'Team Lead',
        organizationId: 'ops',
        departmentId: 'ops-core',
        groupIds: [],
        personId: 'p-lead',
        status: 'filled',
        isTemporary: false,
      },
      {
        id: 'pos-a',
        title: 'Specialist A',
        organizationId: 'ops',
        departmentId: 'ops-core',
        groupIds: [],
        personId: 'p-a',
        status: 'filled',
        isTemporary: false,
      },
      {
        id: 'pos-b',
        title: 'Specialist B',
        organizationId: 'ops',
        departmentId: 'ops-core',
        groupIds: [],
        personId: 'p-b',
        status: 'filled',
        isTemporary: true,
      },
      {
        id: 'pos-eng-h',
        title: 'Eng Head',
        organizationId: 'eng',
        departmentId: 'eng-core',
        groupIds: [],
        personId: 'p-eng-h',
        status: 'filled',
        isTemporary: false,
        isHead: true,
      },
      {
        id: 'pos-dev',
        title: 'Developer',
        organizationId: 'eng',
        departmentId: 'eng-core',
        groupIds: [],
        personId: 'p-dev',
        status: 'filled',
        isTemporary: false,
      },
    ],
    reportLines: [
      { fromId: 'pos-coo', toId: 'pos-lead', kind: 'admin' },
      { fromId: 'pos-lead', toId: 'pos-a', kind: 'admin' },
      { fromId: 'pos-lead', toId: 'pos-b', kind: 'admin' },
      { fromId: 'pos-a', toId: 'pos-b', kind: 'matrix' },
      { fromId: 'pos-eng-h', toId: 'pos-dev', kind: 'admin' },
    ],
  };
}
